### PR TITLE
[bug fix] Prevent `update_cache()` from removing uninstalled Python dependencies from `requirements.txt`

### LINKED ISSUE #68: `sandpaper::update_cache()` should not clear contents of `requirements.txt`
When running `sandpaper::update_cache()`, the contents for `requirements.txt` get unintentionally removed if the Python packages are not yet installed locally on the system.

## Reprex

```r
# Add a non-installed package to requirements.txt
writeLines("imnotinstalled", "requirements.txt")

req <- readLines("requirements.txt")
"imnotinstalled" %in% req
#> [1] TRUE

sandpaper::update_cache()

req <- readLines("requirements.txt")
"imnotinstalled" %in% req
#> [1] FALSE
```

### PR DESCRIPTION
**Pull request by milanmlft**
- Call `manage_deps()` before updating cache to ensure all current requirements (including Python ones) are installed
- Refactor `update_cache()` to use `with_renv_factory()` to run `renv` tasks in separate R processes, this avoids some annoying side effects like opening new RStudio sessions when testing code interactively

Fixes #68 
Related: https://github.com/milanmlft/sandpaper/pull/23

### CODE REVIEW

File: tests/testthat/test-manage_deps.R [hunk 1]
```diff
@@ -242,9 +246,23 @@ test_that("manage_deps() restores Python dependencies", {
...
+test_that("update_cache does not remove uninstalled Python dependencies from requirements.txt", {
+  skip_if_not(reticulate_installable, "reticulate is not installable")
+  skip_on_cran()
+  skip_on_os("windows")
+
+  req_file <- fs::path(lsn, "requirements.txt")
+  write("pandas", req_file, append = TRUE, sep = "\n")
+
+  res <- update_cache(lsn, prompt = FALSE, quiet = FALSE)
+  expect_true(any(grepl("pandas", readLines(req_file))))
```
Comment (dpshelio) [inline tests/testthat/test-manage_deps.R]: Maybe a smaller library (and something we for sure won't use), with a smaller footprint could make this test faster. e.g., [`art`](https://github.com/sepandhaghighi/art).

File: R/manage_deps.R [hunk 2]
```diff
@@ -104,18 +104,31 @@ manage_deps <- function(path = ".", profile = "lesson-requirements", snapshot =
...
 #' @rdname dependency_management
 #' @export
-update_cache <- function(path = ".", profile = "lesson-requirements", prompt = interactive(), quiet = !prompt, snapshot = TRUE) {
-  path <- root_path(path)
+update_cache <- function(path = ".", profile = "lesson-requirements", prompt = interactive(),
+                         quiet = !prompt, snapshot = TRUE) {
+
   prof <- Sys.getenv("RENV_PROFILE")
   on.exit({
-    invisible(utils::capture.output(renv::deactivate(path), type = "message"))
```
Comment (dpshelio) [inline R/manage_deps.R:111]: Does it affect capturing the output in this case? I don't really understand what `invisible` does though.

**Review by dpshelio — APPROVED** [review]
Looks fine to me... I'm happy to approve it. I've left two small comments for you to consider if they are helpful.

File: R/manage_deps.R (hunk 2 above)
Comment (milanmlft) [reply R/manage_deps.R:111]: This bit was moved to `with_renv_factory()` so it will still get executed

- `capture.output()` is used here mainly to suppress the info messages from `renv` (which we don't care about here)
- `inivisble()` returns the output invisibly, in this instance it's again a little "hack" to suppress output

**Review by sabaferdous12 — APPROVED** [review]
